### ISSUE TITLE
Issue with TypeError

### ISSUE THREAD

**Issue by chaochii** [simonewebdesign/websocket-demo#1]
I installed all the packages and the server.js, but once I open the index.html. Following message has been shown...

```
`connection.on('message', function(message) {
             ^

TypeError: Cannot read property 'on' of undefined
    at WebSocketServer.<anonymous> (/Users/Chaoyi/Downloads/websocket-demo-master/server.js:48:14)
    at WebSocketServer.emit (events.js:182:13)
    at WebSocketServer.handleUpgrade (/Users/Chaoyi/Downloads/websocket-demo-master/node_modules/websocket/lib/WebSocketServer.js:213:14)
    at Server.emit (events.js:182:13)
    at onParserExecuteCommon (_http_server.js:535:14)
    at onParserExecute (_http_server.js:482:3)`
```

**Comment by simonewebdesign** [comment]
This was happening because the connection was requested by an origin that wasn't allowed. The connection got rejected, making `connection` undefined and crashing the server. I fixed this by relaxing the origin check in f7a90bd8a30d8e929c03883217f6c030545bf1cb. Thanks for reporting!
